[package]
name = "easydep"
version = "0.1.0"
authors = ["easybill"]

edition = "2021"
rust-version = "1.56.1" # 2021 edition requires 1.56

license = "MIT"
publish = false
repository = "https://github.com/easybill/easydep"
description = "An HTTP driven, server side deployment executing tool"

[profile.release]
lto = true
strip = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1

[dependencies]
anyhow = "*"
axum = "0.6.*"
serde = "1.0.*"
chrono = "0.4.*"
cached = "0.42.*"
secrecy = "0.8.*"
symlink = "0.1.*"
fs_extra = "1.3.*"
crossbeam = "0.8.*"
serde_derive = "1.0.*"
jsonwebtoken = "8.2.*"
tokio = { version = "1.26.*", features = ["full"] }
clap = { version = "4.1.*", features = ["derive", "env"] }
octocrab = { version = "0.18.*", features = ["rustls-tls"], default-features = false }

# logging
log = "0.4.*"
syslog = "6.0.*"
simple_logger = "4.0.*"
