name: Checks
on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:

concurrency:
  cancel-in-progress: true
  group: checks-${{ github.event.pull_request.number || github.ref }}

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / fmt
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ "stable", "nightly" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: ${{ matrix.toolchain }}
      - name: Cargo fmt
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ "stable", "nightly" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
      - name: Setup Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cargo clippy
        uses: clechasseur/rs-clippy-check@v3
