name: "CI"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: Publish Release

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    permissions: read-all
    runs-on: ${{ matrix.platform.os }}
    name: Compile ${{ matrix.platform.target }} / ${{ matrix.platform.os }}

    strategy:
      fail-fast: true
      matrix:
        platform:
          # mac target
          - { os: 'macos-latest', target: 'x86_64-apple-darwin', arch: 'x86_64', osn: 'mac' }
          - { os: 'macos-latest', target: 'aarch64-apple-darwin', arch: 'aarch64', osn: 'mac' }
          # linux target
          - { os: 'ubuntu-latest', target: 'x86_64-unknown-linux-musl', arch: 'x86_64', osn: 'linux' }
          - { os: 'ubuntu-latest', target: 'aarch64-unknown-linux-musl', arch: 'aarch64', osn: 'linux' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          target: ${{ matrix.platform.target }}

      - name: Initialize Rust caching
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.target }}

      - name: Compile Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target ${{ matrix.platform.target }} --bin easydep

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: target/${{ matrix.platform.target }}/release/easydep
          name: easydep_${{ matrix.platform.osn }}_${{ matrix.platform.arch }}

  release:
    needs: [ "build" ]
    name: Publish Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true' }}

    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Build tag name
        env:
          RUN: ${{ github.run_number }}
          ATTEMPT: ${{ github.run_attempt }}
        run: echo "TAG_NAME=1.$RUN.$(($ATTEMPT - 1))" >> $GITHUB_ENV;

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: binaries

      - name: Generate changelog
        id: changelog_generate
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignorePreReleases: true
          toTag: ${{ github.sha }}
          configurationJson: '{"max_tags_to_fetch":5,"categories":[],"template":"#{{UNCATEGORIZED}}","pr_template":"- #{{TITLE}} (##{{NUMBER}} by #{{AUTHOR}})"}'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.TAG_NAME }}
          body: ${{steps.changelog_generate.outputs.changelog}}
          fail_on_unmatched_files: true
          files: |
            binaries/*/*
