name: "CI"
on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          check-latest: true
          cache: 'gradle'

      - name: Compile
        run: ./gradlew build --no-daemon --stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' }}
        with:
          name: Easydep
          path: build/libs/easydep.jar
