name: "Draft new release"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Draft new release

    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          check-latest: true
          cache: 'gradle'

      - name: Compile
        run: ./gradlew build --no-daemon --stacktrace

      - name: Resolve project version
        run: echo "VERSION=$(./gradlew properties | awk '/^version:/ { print $2; }')+b${{ github.run_number }}" >> $GITHUB_ENV;

      - name: Generate changelog
        id: changelog_generate
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignorePreReleases: true
          toTag: ${{ github.sha }}
          configurationJson: '{"max_tags_to_fetch":5,"categories":[],"template":"#{{UNCATEGORIZED}}","pr_template":"- #{{TITLE}} (##{{NUMBER}} by #{{AUTHOR}})"}'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.VERSION }}
          body: ${{steps.changelog_generate.outputs.changelog}}
          fail_on_unmatched_files: true
          files: |
            build/libs/easydep.jar
